### ISSUE TITLE
"date received" should be sent to medic-api for WT messages

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-gateway#11]

**Comment by alxndrsn** [comment]
Currently the date of WT messages will be the date that the message was received at `medic-webapp`.  @abbyad is this the expected behaviour?

**Comment by mandric** [comment]
Currently I'm pretty sure the `reported_date` of the record is set to the "sent_timestamp" of the message... so pretty sure  that means the `reported_date` is set to when the message was sent from the mobile device or when it was reported. Not when it reached the server.

**Comment by alxndrsn** [comment]
@mandric messages coming from `medic-gateway` do not have `reported_date` set: https://github.com/medic/medic-api/blob/master/controllers/sms-gateway.js#L36 - note that `reported_date` is an optional field at https://github.com/medic/medic-api/blob/master/controllers/records.js#L23.

@abbyad has reported that he is not seeing the dates he is expecting for these messages, so I am interested to hear from him:

1. what dates he _is_ seeing, and
2. how these differ from what he'd expect

**Comment by mandric** [comment]
@alxndrsn they should.  The timestamp for message should be set to when they were either sent by the device or received by the gateway.  Currently SMSSync uses the "sent_timestamp" in the message so that is what @abbyad would expect.

**Comment by mandric** [comment]
Related: https://github.com/ushahidi/SMSSync/blob/master/smssync/src/main/java/org/addhen/smssync/data/net/MessageHttpClient.java#L125

**Comment by abbyad** [comment]
I can see it being useful to have *both* the time it was received by the webapp, and the time it was sent by the user -- for which the time it was received by the gateway is our proxy. 

If Gateway passes the reported_date as the time the SMS was sent (or received) then we can get the webapp time from https://github.com/medic/medic-webapp/issues/2180.

**Comment by alxndrsn** [comment]
Would be fixed by #37?

**Comment by mandric** [comment]
Sure it would be nice to have both but that's a different ticket right?  That's the "creation date" or "replicated date" which is another can of worms.  For now we just want the same behavior/backwards compatibility.
