### ISSUE TITLE
Gateway APK for production that mutes old messages from Webapp. 

### ISSUE THREAD

**Issue by ngamita** [medic/medic-gateway#110]
Following slack discussion on a requirement to mute messages in production feature for the medic gateway. We already have this feature for testing APK. Please go ahead and add this new feature on the next versions of the medic gateway.

**Comment by sglangevin** [comment]
@alxndrsn leaving this one to you. This is a really useful feature (in fact, I used the testing APK while in Nairobi) so it would be great to include it in the next APK release!

**Comment by kennsippell** [comment]
No idea what this 2017 issue is about. Please re-activate if deemed useful.
