### ISSUE TITLE
Change from cwac-wakeful to JobIntentService

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-gateway#129]
As per https://github.com/commonsguy/cwac-wakeful, cwac-wakeful is deprecated and should be replaced with [`JobIntentService`](https://developer.android.com/reference/android/support/v4/app/JobIntentService.html).

We're having reliability problems anyway with devices failing to wake up when they should (https://github.com/medic/medic-gateway/issues/127, https://github.com/medic/medic-gateway/issues/126); this change may fix those problems.

**Comment by alxndrsn** [comment]
Try https://github.com/evernote/android-job

**Comment by alxndrsn** [comment]
Or https://github.com/firebase/firebase-jobdispatcher-android

Or:
1. in `BroadcastReceiver` implementation, send incoming SMS to webapp
2. get webapp to forward SMSs to the handset using FCM

**Comment by MaxDiz** [comment]
may be duplicate with #147

**Comment by garethbowen** [comment]
Agreed. Closing as duplicate.
