### ISSUE TITLE
Request to publish generic build apks

### ISSUE THREAD

**Issue by 50csent** [medic/medic-gateway#133]
Please consider also publishing generic build apks in addition to medic branded builds.  I'm exploring the possibility of using medic-gateway in internally used webapp and hadn't I found bitrise.io I would probably never succeed in building generic release myself.

**Comment by alxndrsn** [comment]
@50csent sorry for the slow response.  The 1.6.0 generic APK should be available now from https://github.com/medic/medic-gateway/releases, and future releases will also appear there.
