### ISSUE TITLE
should be able to disable polling even if URL won't validate

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-gateway#14]
If the URL has not changed and the user is trying to disable polling, the URL should not be verified.  A simple approach to this might be just to ignore verification when polling is disabled.

**Comment by alxndrsn** [comment]
Implemented at https://github.com/medic/medic-gateway/tree/dont-validate-if-polling-disabled; needs unit test and on-device testing.

**Comment by alxndrsn** [comment]
Fixed in https://github.com/medic/medic-gateway/commit/3052e717ff7fb20105bc92720bdcdecc29e918af

**Comment by mandric** [comment]
Any reason this skips code review?

**Comment by alxndrsn** [comment]
@mandric didn't seem like it needs it, but feel free if you want to
