### ISSUE TITLE
Mark messages as received-by-gateway so they are not included in the next response 

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-gateway#142]
From medic/medic-webapp#3073 :
Modify medic-gateway to call medic-api and change the status of received messages to received-by-gateway after they have been successfully written to the database. This will stop them being sent again next query and reduce the bandwidth requirements.

This will avoid step 4 in [the current protocol](https://github.com/medic/medic-docs/blob/e4483cbae3b619f1db8f1990f43cd25905e7b09d/user/message-states.md)

To do it, have gateway set the `needs forwarding` flag to `true` when storing a new message in DB.

**Comment by garethbowen** [comment]
This looks like it's mostly done. Scheduling for 3.5.0 to align with the other gateway work.

**Comment by garethbowen** [comment]
Not yet started - delaying to 3.9.0

**Comment by garethbowen** [comment]
Delaying as this is a performance improvement only.

**Comment by latin-panda** [comment]
Moving to AT, PR: https://github.com/medic/medic-gateway/pull/160

**Comment by latin-panda** [comment]
### Summary
The issue is when API send to Gateway a message (sms), this message was being saved as "not needing forwarding", so its status wasn't updated as "received by gateway" and API might try to send it again to Gateway.

The fix is:
The SMS status should be set as `Needs Forwarding` when updating sms statuses or when saving new SMS to Gateway DB. Then Gateway will notify the status change to API from the beginning, reducing the chance of API to resend the same SMS to Gateway.

It's important to note that API <-> Gateway communicates in intervals of time, every 2 or 5 minutes.

**Comment by newtewt** [comment]
@latin-panda  I think this is ready to go. 

I've pulled the sqlite database and see the message is marked with `needs_forwarding` of 1. Once the attempt to send and it eventually fails. The `needs_forwarding` is marked as 0. Looking at the `status_history` on the message in couchdb. I see the proper flow through. As shown below.  Also, have ensured on my phone with service that the messages are being sent properly. 



``` 
      "state_history": [
        {
          "state": "pending",
          "timestamp": "2020-09-28T14:28:06.231Z"
        },
        {
          "state": "forwarded-to-gateway",
          "timestamp": "2020-09-28T14:28:58.170Z"
        },
        {
          "state": "received-by-gateway",
          "timestamp": "2020-09-28T14:29:58.089Z"
        },
        {
          "state": "forwarded-by-gateway",
          "timestamp": "2020-09-28T14:29:58.089Z"
        },
        {
          "state": "failed",
          "state_details": {
            "reason": "generic; errorCode=-1"
          },
          "timestamp": "2020-09-28T14:29:58.089Z"
        }
```

**Comment by garethbowen** [comment]
@latin-panda Can this issue be closed now?

**Comment by latin-panda** [comment]
Hi @garethbowen, yes, it's in "done" status and code was merged :)
