### ISSUE TITLE
On newer android devices the Help Me Change button doesn't work

### ISSUE THREAD

**Issue by newtewt** [medic/medic-gateway#164]
# Instructions

Gateway prompts the user to set this app as the default SMS app. When pressing the button nothing occurs. 

## Log files

`2020-09-16 20:02:02.881 13051-13051/medic.gateway.alert.generic I/MedicGateway: onActivityResult() :: returned from SMS app settings.  resultCode=0, data=null`

## Device details

For each device, please fill in a column of the **Device(s) tested** table.

-----

# Device(s) tested

Device | Android version | medic-gateway version | problem recreated?
---|---|---|---|
Google Pixel2 | 11 | master | yes
Google Pixel1 | 10 | 1.7.4 | no
Google Pixel1 | 10 | 1.5.1 | no
Google Pixel1 | 10 |  [135 branch](https://github.com/medic/medic-gateway/pull/161) | yes

# Observed behavior

When "Help me change" button is clicked, I don't see a modal shown:

[<img src="https://user-images.githubusercontent.com/8253488/109848717-6d939000-7c05-11eb-863e-0d81afc13916.png" width=40% height=40%>](https://user-images.githubusercontent.com/8253488/109848717-6d939000-7c05-11eb-863e-0d81afc13916.png)

# Expected behavior

Should navigate to the settings to set gateway as the default sms device as seen here:

[<img src="https://user-images.githubusercontent.com/8253488/109848740-73897100-7c05-11eb-9ad8-6a86b268c73b.png" width=40% height=40%>](https://user-images.githubusercontent.com/8253488/109848740-73897100-7c05-11eb-9ad8-6a86b268c73b.png)

# Steps to recreate

Using Android 11 
Install Gateway
When asked to set gateway as the default messaging device the button for "Help Me Change" does not take the user anywhere.

**Comment by mrjones-plip** [comment]
@newtewt  - you wanna put the hash deep link for the revision of master` you tested?  Otherwise `master` is a moving target, yeah?

**Comment by garethbowen** [comment]
The workaround for this is to manually set the default SMS app through Android settings.

**Comment by ngaruko** [comment]
LGTM
Tested on the branch with `android 10`.
![image](https://user-images.githubusercontent.com/6979995/116959537-fc01bc00-acf1-11eb-9e4b-76c3ee189bcf.png)
 and
![image](https://user-images.githubusercontent.com/6979995/116959589-13d94000-acf2-11eb-976b-cdc6de629df9.png)

**Comment by garethbowen** [comment]
@latin-panda Thanks! It looks like v1.8.2 is ready for release. What do you think?

**Comment by latin-panda** [comment]
Hi @garethbowen There's one more issue to verify in Android +10: https://github.com/medic/medic-gateway/issues/175
I'm suggesting to retry, since I didn't have trouble connecting with `https://[user]:[pass]@[server]/api/sms`, waiting for @ngaruko feedback.

**Comment by ngaruko** [comment]
Will try this @latin-panda

**Comment by latin-panda** [comment]
@garethbowen I think all tickets related to Android +10 has been addressed and looks like nothing else is scheduled for this release. I'd say it's good for a release :)
