### ISSUE TITLE
Medic Gateway stopped polling automatically

### ISSUE THREAD

**Issue by bishwas-medic** [medic/medic-gateway#25]
Phone model: Samsung Galaxy J7
Android version: 6.0.1
Project URL: https://rolpa-eyehealth.app.medicmobile.org

SMS aren’t being synced and forwarded. Even the `Compose` function is not working. Logs suggests that it stopped polling the webapp automatically after a day. Stopping and starting the polling from Settings also didn't work. Also, the `Retry` function doesn’t do anything on both incoming and outgoing messages.

**Comment by alxndrsn** [comment]
Please share the logs from the misbehaving phone with me directly.

Some queries:

* did restarting the handset restore expected functionality?
* can you reliably recreate the problem?
* do you know the amount of free space left on the device when the problem occurred?
* have there been reports of the same problem on other handsets?

**Comment by bishwas-medic** [comment]
Alexy, currently out of office for few days. I'll share the logs when I'm at the office next time.

For the questions:
- I didn't restart and check as it was a live project and reports were coming in. I'll test that on a coming weekend.
- I don't think I can recreate the issue exactly. This happened out of blue and didn't have any clues regarding what caused it to stop polling abruptly
- There was plenty of free space on the device. There were no lags in other apps or slow responses to user actions.
- No similar problems in other handsets.

**Comment by bishwas-medic** [comment]
Updates on this issue:
- Restarted the phone in the morning and Medic Gateway started polling again. There has been no issues so far.
- Will check the phone daily for few days now to see if it happens again and report back with proper logs in such case.

**Comment by alxndrsn** [comment]
Great, thanks for the update @bishwas-medic

**Comment by alxndrsn** [comment]
Please re-open if the problem persists.
