### ISSUE TITLE
delete old logs to free space and prevent phone slowdown

### ISSUE THREAD

**Issue by bishwas-medic** [medic/medic-gateway#27]
It's been observed that gateway phones used in high SMS traffic projects are being slowed down as the logs pile up. Phones with lower RAM (512 MB) are very much effected with the phones being almost unusable. Even phones with higher RAM (2 GB) are getting slow to touch and user actions.

It'd be great to have an auto deletion feature that clears out the logs older than a certain period of time. Or when logs exceed a certain size of the available disk space.

**Comment by alxndrsn** [comment]
Suggested implementation:
Menu item: _Clear old data_
`->` dialog: _Warning: this will delete all event logs and messages that are more than one week old._  [ **Delete** ] [ **Cancel** ]

**Comment by bishwas-medic** [comment]
I think we should include an auto-deletion feature too? As most of the times the gateway phones are handled by non-technical staffs of our partners. As we've experienced before, they will tend to forget to monitor the phone on regular basis and clear of the old logs manually.

**Comment by alxndrsn** [comment]
@bishwas-medic should old messages be deleted if they were **not** successful?  E.g. in one of the following states:
* pending
* failed to send
* not yet uploaded to webapp

I can see arguments both ways...
