### ISSUE TITLE
message delivered without being sent

### ISSUE THREAD

**Issue by mandric** [medic/medic-gateway#31]
Was looking at the message history of a doc and noticed a message was delivered without being sent.  Is that normal or expected?  Wondering how that might have happened.

See the first item listed under `.tasks`:
```
curl https://v2-test-person-centered-anc.app.medicmobile.org/medic/072b93ef15d595ff28ad917a65b41483 | jq '.tasks[0]'
```

**Comment by alxndrsn** [comment]
If the message is both sent _and_ delivered between pollings of the webapp, only the delivery will be reported.

**Comment by mandric** [comment]
So it's likely the message was sent and delivered within 5 seconds (default polling time)?

**Comment by mandric** [comment]
Maybe this history is worth an explanation/ponder:

```
  "state": "delivered",
  "state_history": [
    {
      "state": "pending",
      "timestamp": "2016-12-01T06:49:12.554Z"
    },
    {
      "state": "scheduled",
      "timestamp": "2016-12-01T06:49:26.571Z"
    },
    {
      "state": "delivered",
      "timestamp": "2016-12-01T06:49:47.449Z"
    }
  ]
```

**Comment by alxndrsn** [comment]
Sounds reasonable, although I think the polling time is 30s.

**Comment by alxndrsn** [comment]
If #37 is implemented, gateway could provide all status updates to the server (which would fix this issue).
