### ISSUE TITLE
Forward webapp-terminating messages immediately

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-gateway#48]
_Consider_ forwarding webapp-terminating messages immediately that they are received to medic-gateway.  Consider that any autoreplies triggered will likely still not be available until the next poll is made (depending on how/where/when api/webapp/sentinel generates these replies).

**Comment by garethbowen** [comment]
@SCdF This is a duplicate of #138 right?

**Comment by SCdF** [comment]
Yes! 

> Consider that any autoreplies triggered will likely still not be available

Is also covered by us making sentinel sync for SMS.
