### ISSUE TITLE
Maintain external list of unsynced WT messages

### ISSUE THREAD

**Issue by bishwas-medic** [medic/medic-gateway#49]
## Problem
All the incoming messages from users are stored in Medic Gateway as it is used as the default SMS app for the phone. There has been a situation where the app had completely stopped working due to the memory issue and all the app data had to be erased from the Adnroid's app setings to free up space. In the process, it also deleted all the messages that were not synced with the webapp. There wasn't anyway to recover those messages and get to sync them back with webapp. In case of unsent messages originating from the webapp, we do not have to worry as they will still have the `pending` status and will be sent later when the app is restarted.

## Possible solution
Saving unsynced messages on a separate file on a different file location will be a good option. In case of such app failures, user can simply import the messages from the files and the app will sync it back with webapp, thus eliminating any chances of lost reports.

**Comment by alxndrsn** [comment]
Are there problems with leaving SMS data on the file system, where:

* other apps can read it, and
* it will persist after gateway has been uninstalled?

-----

If there is no space left on the device, how are we meant to persist anything to anywhere without getting some kind of out-of-storage-space error?

-----

One simple idea:

* when a message arrives, append its details to `received_sms.log`.  Make sure that this write has flushed to disk before continuing with message processing
* when the app restarts, before doing other stuff:
  - read `received_sms.log`
  - for each entry in the file, check if we already have a WtMessage in the db with matching sender and content.  if we do not, then store the new WoMessage
  - clear contents of `received_sms.log`

**Comment by bishwas-medic** [comment]
That sounds like a good solution.

About the persistence of the file, it shouldn't be deleted during the uninstallation of Medic Gateway so that we can use it after the Gateway is uninstalled again. The issue with the space will always be tricky to deal with unless we do something like syncing it with some online file storage system (adding another layer of complexity for things to go wrong). But we can still be sure that we have a failsafe when the Medic Gateway stops working and needs reinstalling for other reasons beside phone running out of space.

**Comment by alxndrsn** [comment]
> About the persistence of the file, it shouldn't be deleted during the uninstallation of Medic Gateway so that we can use it after the Gateway is uninstalled again.

As you point out, there are definite advantages to this - as long as we keep in mind that this file will hang around on handsets even after they have stopped being used as a gateway phone.

**Comment by bishwas-medic** [comment]
How about encrypting the file? (Kidding)

I think people having access to the file will be a smaller concern than losing out a bunch of received reports.
