### ISSUE TITLE
Sending long SMS from GSM to CDMA handsets doesn't work

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-gateway#57]
Sending multipart SMS from a GSM gateway to a CDMA phone does not work reliably.  Either only the first part of the message arrives, or nothing arrives at all.  (Likely only one of these behaviours has been observed - clarify via team or testing to work out which).

**Comment by alxndrsn** [comment]
This issue got a passing mention at https://github.com/medic/medic-webapp/issues/670

**Comment by bishwas-medic** [comment]
I can confirm that while sending multipart SMS to CDMA phones, only the first part of the message is delivered. Sometimes, nothing gets delivered. We've encountered that issue in one of our projects (Baglung) and had to adjust the scheduled reminders and replies to fit one SMS length.

**Comment by alxndrsn** [comment]
It looks like this is a property of _some_ CDMA networks.  In which case, we might offer a "CDMA compatibility" mode option in gateway to split the messages into separate parts before sending.

@bishwas-medic can you confirm if this happens with both NCell and NTC CDMA phones, or just one of the networks?

**Comment by alxndrsn** [comment]
Some things to note:
* max character count may be 140 (or 70 for UCS2) in CDMA SMS
* might be helpful to prefix `n/N` to each part (e.g. `1/3 `, `2/3 `, `3/3 `)

**Comment by browndav** [comment]
I saw something similar happen between two GSM providers in the US; messages going in one direction between AT&T and T-mobile appeared to have the GSM UDH stripped or rewritten, causing multipart messages to effectively become a series of single messages.

**Comment by bishwas-medic** [comment]
@alxndrsn Ncell doesn't have a CDMA network. I think NTC is the only telecom IN Nepal with the CDMA network.

And yeah , the max character for each SMS in CDMA network is 140.
