### ISSUE TITLE
Status history for WT messages

### ISSUE THREAD

**Issue by bishwas-medic** [medic/medic-gateway#76]
If we click on any message in the list on `TO WEBAPP` tab, a pop-up appears with details about the message which includes the `Status` and time of `Last action` for the message. 

I'd like to also see the time when the message was received on the phone and the time when it was successfully forwarded to the webapp. It should show the exact time and date instead of just saying "<some> hours ago". This would be helpful while trying to figure out if there was any delay between receiving and forwarding of the message. Will also help to confidently inform users that the delay in receiving replies was due to the network issues.

**Comment by alxndrsn** [comment]
Possible dates to record:

* sent by originator
* received at gateway
* forwarded to webapp

Once this is implemented, consider which of these dates should be forwarded to the webapp.

**Comment by bishwas-medic** [comment]
I think, these should suffice: 
- received at gateway
- forwarded to webapp
- forward failed

**Comment by estellecomment** [comment]
I'm going to add a DB table for status history, with columns : 
`message id, new status, timestamp of new status`
With status = `WAITING, FORWARDED, FAILED`

And if we want to store `SENT_FROM_PHONE` status or whatever else later, it'll allow that easily.

**Comment by mandric** [comment]
Wouldn't it be useful to record all those dates including "sent by originator" I think that might be the date we used in smssync called 'sent_timestamp' which gets translated to 'reported_date' on the record.  Just future thinking here if we wanted backwards compatibility or at least a reference to something if people get confused about dates when migrating to 2.x.

**Comment by estellecomment** [comment]
Yup we can do that, in this issue or a separate one.

**Comment by estellecomment** [comment]
@alxndrsn Can you rereview please? https://github.com/medic/medic-gateway/pull/79/files

**Comment by alxndrsn** [comment]
Fixed in 1.2.0.
