### ISSUE TITLE
Medic-Gateway breaks when using a longer password

### ISSUE THREAD

**Issue by erwagasore** [medic/medic-gateway#80]
version:  v1.0.0
phone:    Google Pixel
android:  Android nougat (v7.1.2)
--
Medic-Gateway application exits when saving settings with a very long password.

**Comment by alxndrsn** [comment]
@erwagasore thanks for the report - I'll look into it.

Can you please provide a log of the crash?

Also bear in mind that we haven't tested with this model previously, and I don't have access to one, so there may be other issues as well.

**Comment by erwagasore** [comment]
Sorry for the delay. I didn't have a proper cable

**Comment by erwagasore** [comment]
Here is the log file
[medic-gateway-log.txt](https://github.com/medic/medic-gateway/files/887477/medic-gateway-log.txt)
