### ISSUE TITLE
Gateway stats summary request. 

### ISSUE THREAD

**Issue by ngamita** [medic/medic-gateway#94]
It would be a good feature to add to the gateway or data pushed to the webapp on the number of sms'es being received to/fro gateway. Accounts and PMs always coming around with questions like - Hey for variations, would you know the number of SMS the gateway sends per month?or the number of messages received from CHVs per month on average - so that they can plan ahead on how much($$) partners need to add as credit to gateways or for budgeting purposes.  cc @alxndrsn

**Comment by alxndrsn** [comment]
- [ ] rename _About_ to _Message statistics_
- [ ] use proper SQL
